# Generated by Django 2.1.5 on 2019-01-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='clientepublicacao',
            options={'verbose_name': 'Cliente Publicação', 'verbose_name_plural': 'Cliente Publicações'},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.AddField(
            model_name='postagem',
            name='categoria',
            field=models.CharField(choices=[('Bolo de Aniversário', 'Bolo de Aniversário'), ('Bolo de Casamento', 'Bolo de Casamento'), ('Cupcake', 'Cupcake'), ('Rocambole', 'Rocambole'), ('Bolo de camadas', 'Bolo de camadas')], default='', max_length=40, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço'),
        ),
    ]
