# Generated by Django 2.1.3 on 2019-01-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190107_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confeiteiro',
            old_name='Senha',
            new_name='senha',
        ),
        migrations.AlterField(
            model_name='confeiteiro',
            name='cidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='confeiteiro',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='confeiteiro',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='confeiteiro',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
